# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMl6y4dKpXJmVB8zHmWUrBid4FhdSqd0
"""

!pip install matplotlib seaborn scikit-learn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('Real_Estate_Data.csv')
def clean_price(val):
    val = str(val).replace('₹', '').replace(',', '').strip().lower()
    if 'cr' in val:
        try:
            return float(val.replace('cr', '').strip()) * 100
        except:
            return np.nan
    elif 'l' in val:
        try:
            return float(val.replace('l', '').strip())
        except:
            return np.nan
    else:
        return np.nan
df['Cleaned_Price(Lakhs)'] = df['Price'].apply(clean_price)
df.dropna(subset=['Cleaned_Price(Lakhs)'], inplace=True)
df.drop(['Price'], axis=1, inplace=True)
df.fillna(method='ffill', inplace=True)

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import time
print(df.info())
print(df.describe())
plt.figure(figsize=(8,4))
sns.histplot(df['Cleaned_Price(Lakhs)'], bins=50, kde=True)
plt.title('Distribution of Prices (in Lakhs)')
plt.show()
df_encoded = pd.get_dummies(df, drop_first=True)
X = df_encoded.drop('Cleaned_Price(Lakhs)', axis=1)
y = df_encoded['Cleaned_Price(Lakhs)']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("R2 Score:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred, alpha=0.5)
plt.xlabel("Actual Price (Lakhs)")
plt.ylabel("Predicted Price (Lakhs)")
plt.title("Actual vs Predicted Prices")
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--')
plt.show()
importances = model.feature_importances_
feat_names = X.columns
imp_df = pd.DataFrame({'Feature': feat_names, 'Importance': importances})
imp_df.sort_values(by='Importance', ascending=False, inplace=True)
plt.figure(figsize=(10,6))
sns.barplot(x='Importance', y='Feature', data=imp_df.head(10))
plt.title('Top 10 Important Features')
plt.show()
import joblib
joblib.dump(model, 'house_price_model.pkl')
print("Model saved for deployment.")